name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'force-app/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Install Salesforce CLI from NPM
        run: npm install @salesforce/cli@2.108.6 --global
          
      - name: Write the dev hub token into a file
        run: 'echo ${{secrets.SFDX_AUTH_URL}} > sfdx-auth-url'
        
      - name: Authenticate with the dev hub
        run: sf org login sfdx-url --sfdx-url-file sfdx-auth-url --alias dev-hub --set-default-dev-hub
        
      - name: Create scratch org
        run: sf org create scratch --definition-file config/project-scratch-def.json --alias test-scratch --set-default
        
      - name: Push source
        run: sf project deploy start
          
      - name: Run tests
        run: sf apex run test --synchronous --code-coverage --result-format human --output-dir ./tests/apex

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          flags: Apex
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Delete scratch org
        if: always()
        run: sf org delete scratch --no-prompt
